# Docker Compose override for development
# This file is automatically loaded by docker-compose for local development
version: '3.8'

services:
  fastapi:
    # Enable live code reloading for development
    volumes:
      - ./src:/app/src
    environment:
      - LOG_LEVEL=debug
    # Expose FastAPI directly for debugging
    ports:
      - '8000:8000'

  nginx:
    # Mount local static files for development
    volumes:
      - ./src/piper_teleop/web_server/web-ui:/usr/share/nginx/html
