version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: docker/fastapi.dockerfile
    container_name: tactile-teleop-api
    restart: unless-stopped
    env_file:
      - ${ENV_FILE:-development.env} # Domain and deployment configuration
      - .env # API keys and secrets
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - tactile-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    container_name: tactile-teleop-nginx
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
      args:
        DOMAIN_NAME: ${DOMAIN_NAME:-localhost}
    networks:
      - tactile-network
    env_file:
      - ${ENV_FILE:-development.env} # Domain and deployment configuration
      - .env # API keys and secrets
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:-localhost}
    ports:
      - '${NGINX_HTTP_PORT:-8080}:80' # HTTP
      - '${NGINX_HTTPS_PORT:-8443}:443' # HTTPS
    volumes:
      # Let's Encrypt certificates (direct mount from system)
      - /etc/letsencrypt:/etc/letsencrypt:ro
      # Certbot challenges for renewal
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      fastapi:
        condition: service_healthy
    healthcheck:
      test:
        [
          'CMD',
          'sh',
          '-c',
          'curl -k -f https://localhost/health || curl -f http://localhost/health',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    command: /bin/sh -c "/docker-entrypoint.d/nginx-and-ssl-setup.sh && (while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g 'daemon off;')"

networks:
  tactile-network:
    driver: bridge
